name: Korsche Scratch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Create images directory
        run: |
          pwd
          ls -l
      
      # - name: Run scratch
      #   run: python src/scratch.py
      #   env:
      #     AWS_REGION: 'us-east-1'
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #     UPLOADER_AWS_ACCESS_KEY: ${{ secrets.UPLOADER_AWS_ACCESS_KEY }}
      #     UPLOADER_AWS_SECRET_KEY: ${{ secrets.UPLOADER_AWS_SECRET_KEY }}
      #     UPLOADER_S3_BUCKET: ${{ vars.UPLOADER_S3_BUCKET }}

      # - name: upload to s3
      #   run: |
      #     pwd
      #     ls images/*
      #     ls images/* | head -n 1
      #     python src/upload.py "$(ls images/* | head -n 1)"
      #   env:
      #     AWS_REGION: 'us-east-1'
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #     UPLOADER_AWS_ACCESS_KEY: ${{ secrets.UPLOADER_AWS_ACCESS_KEY }}
      #     UPLOADER_AWS_SECRET_KEY: ${{ secrets.UPLOADER_AWS_SECRET_KEY }}
      #     UPLOADER_S3_BUCKET: ${{ vars.UPLOADER_S3_BUCKET }}
